#!/bin/bash
xsetroot -cursor_name left_ptr &
setxkbmap "us+bg(phonetic):2+group(alt_shift_toggle)" &
synclient {Vert,Horiz}{Edge,TwoFinger}Scroll=1 TapButton{1=1,2=2,3=3} &
xrdb -merge ~/.xmonad/Xresources
start-pulseaudio-x11 &
compton -m .9 &
sh ~/.fehbg &
/usr/libexec/polkit-gnome-authentication-agent-1 &
stalonetray -t --tint-color black --tint-level 160 -i 24 --geometry 6x1-0+0 --max-geometry 6x1 --grow-gravity E --icon-gravity NE --scrollbars horizontal &
gnome-terminal &
nm-applet &
gpaste-client start &
xscreensaver -nosplash &
utox &
xmobar ~/.xmonad/xmobar &
xrandr --setprovideroffloadsink 1 0
