#!/bin/bash

cp ~/.xmonad/xmonad.hs .
cp ~/.xmonad/Xresources .
cp ~/.xmonad/xmobar .
cp ~/.xmonad/start .
mkdir -p lib/XMonad/Hooks
cp ~/.xmonad/lib/XMonad/Hooks/PerWindowKbdLayout.hs lib/XMonad/Hooks/

git status
